import type { Metadata } from "next";
import localFont from "next/font/local";

import "./globals.css";

const lalezarFont = localFont({
  src: "./Lalezar-Regular.ttf",
});

export const metadata: Metadata = {
  title: "Login",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <body className={`${lalezarFont.className} antialiased `}>
        {children}
      </body>
    </html>
  );
}
